name: Build Sphinx Documentation

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install .
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install ghp-import

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          cd docs
          ghp-import -n -p -f build/html
