name: Build Sphinx Documentation

permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install .
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install ghp-import
          pip install sphinx_design
          pip install myst-nb
          pip install pydata-sphinx-theme
          pip install matplotlib

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
      
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          cname: https://rcjackson.github.io/ADAM
          publish_branch: gh-pages
          

      
